name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t sampleimage:latest

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Registry
        run: |
          docker tag sampleimage ${{ secrets.DOCKER_USERNAME }}/sampleimage
          docker push ${{ secrets.DOCKER_USERNAME }}/sampleimage
